name: VirusTotal scan after released

on:
  release:
    types: [published]

jobs:
  VirusTotal:
    runs-on: ubuntu-latest
    steps:
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v2
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        update_release_body: true
        files: |
          .exe$
